### ISSUE TITLE
Scroll bar not visible

### ISSUE THREAD

**Issue by westofer** [Etesam913/slick-fox#10]
the scroll bar isn't visible which causes a loss in page content. 
I assume this is because of 
https://github.com/Etesam913/slick-fox/blob/17f392f28e2de6509ad1c71d5b14090f0e20c2b5/userChrome.css#L484-L489
changine margin right  -17px to 0 px solves it . is this intentional?

**Comment by Etesam913** [comment]
It was not intentional. Thanks for bringing it up. I just made the change that you suggested.

**Comment by westofer** [comment]
thanks really great theme :heart:
