### ISSUE TITLE
Right click dialog box text is unreadable black in dark themes

### ISSUE THREAD

**Issue by Shadowspear123** [Etesam913/slick-fox#11]
I absolutely love this theme. Just one issue;

The text in the right click dialog box is black in dark themes like the default firefox dark theme and like nord polar dark theme. It makes the text unreadable.
I attached a screenshot;
<img width="320" alt="Screen Shot 2020-12-02 at 11 56 22 PM" src="https://user-images.githubusercontent.com/50462281/100967530-6de49800-34fd-11eb-862d-b7c6c0b27adb.png">

**Comment by Etesam913** [comment]
Just pushed a change, it should be fixed.
