### ISSUE TITLE
Tabs "black" out when hovering mouse over them

### ISSUE THREAD

**Issue by Shadowspear123** [Etesam913/slick-fox#12]
Hi,
The tabs title seems to black out or flicker when you hare hovering your cursor over the tab strip. Screenshot is attached.
<img width="478" alt="Screen Shot 2020-12-03 at 5 17 36 PM" src="https://user-images.githubusercontent.com/50462281/101095212-9c10b900-358b-11eb-9040-2b1f5451e67a.png">

To reproduce, try moving your cursor around over the active tab and watch the tabs in the background get dark.

**Comment by Etesam913** [comment]
Can you show a gif of it or something because I can't seem to reproduce the effect.
It might be a theme specific bug. Does it happen on other bugs as well?

**Comment by Shadowspear123** [comment]
![Screen Recording 2020-12-03 at 7 54 50 PM](https://user-images.githubusercontent.com/50462281/101108723-2add0000-35a3-11eb-9e06-5b9fe297c68f.gif)

**Comment by Shadowspear123** [comment]
I'm using the Nord Polar Dark theme. It happens on the other default firefox themes as well.

**Comment by Etesam913** [comment]
I just pushed a change which hopefully fixes it. However, I can't know for sure as I was not able to replicate it. Let me know if it is fixed after using the new userchrome file.

**Comment by Shadowspear123** [comment]
The issue is fixed in the latest push. Thanks!
