### ISSUE TITLE
Please help with few modifications

### ISSUE THREAD

**Issue by Rtizer-9** [Etesam913/slick-fox#13]
1.  https://ibb.co/SvMj5y0 Since this is only compatible with normal density. Its not working with my compact density for my 13'' screen. Can you at least where to look for modifications.
   2.  Remove every chrome like interface with just autohide functionality working properly without any of the glitches other autohide CSSes had.
   3.  Completely remove all kind of animation and transition so that it appears more slick and fast exception being something like 0.1 seconds. I was able to find every transition and animation code and replace higher seconds with lower but your advise will be better.
   4. Right now, if open something like the hamburger menu or anything from the autohide bar and remove the cursor then the opened menu also goes up with bar getting hidden. I feel like if it doesn't move from its place even after the autohide function then it looks more stable and aesthetic. I was able to achieve that after applying the old autohide from somebody's 7 month old post but the workaround given there for keeping urlbar height normal doesn't work.

Lastly, thanks from the bottom of the heart for making this amazing CSS. Can you please suggest some resources to learn how to do this on your own.

**Comment by westofer** [comment]
but you know this exists right (dev tools for changing chromecss) ? https://www.reddit.com/r/FirefoxCSS/comments/73dvty/tutorial_how_to_create_and_livedebug_userchromecss/

1. I tried changing my resolution to replicate bug number 1 but couldn't :[
can you post your code and resolution/screen size?
