### ISSUE TITLE
URL bar suggestions in Nightly have transparent background

### ISSUE THREAD

**Issue by jchen3652** [Etesam913/slick-fox#19]
Firefox Nightly version 93.0a1 (2021-08-11) (64-bit) on Intel 2019 Macbook Pro

Search suggestions in the URL bar have a transparent background, jumbling suggestions with page contents.

**Comment by kelvin30708** [comment]
Same issue as well ~~

**Comment by chucklay** [comment]
Also applies to right-click menu, seemingly in all contexts.

**Comment by Etesam913** [comment]
I just pushed a bug fix which should fix this. I am not sure if the right-click menu being transparent is also fixed in this change as I presume this is a windows issue (and I can't test on windows currently).

**Comment by chucklay** [comment]
Seems to have fixed both! Thanks!
![image](https://user-images.githubusercontent.com/8353090/133004453-c028f370-3fb0-4cb7-a61a-3c8c0a46f99f.png)
