### ISSUE TITLE
Tabs To Tall

### ISSUE THREAD

**Issue by TwisterMc** [Etesam913/slick-fox#2]
The tabs are too tall on my screen. Not sure if it's an issue with the fonts or something else.

<img width="606" alt="tab issue" src="https://user-images.githubusercontent.com/46997/73996849-73477500-4922-11ea-882e-c58f82dfdf12.png">

**Comment by Etesam913** [comment]
I tweaked some of the margins, but I still do not know if that error will persist. If it does persist, it might be due to the fact that you have your bookmarks bar hidden. Try unhiding it to see if it fixes the issue.

**Comment by Etesam913** [comment]
I think it is fixed now.
