### ISSUE TITLE
Giant URL bar when installed

### ISSUE THREAD

**Issue by isaacsa51** [Etesam913/slick-fox#4]
I just wanna test your userChome.css to change the theme of the browser, after installing it, it shows almost 60% of my screen with the URL bar, I activated all the options you mentioned on the README.
Tested on Windows 10 Pro.
![issue](https://user-images.githubusercontent.com/43853643/88470514-63b0ee00-ceba-11ea-8466-ab6726b19604.jpg)

**Comment by Etesam913** [comment]
This should be fixed. I pushed some recent changes. Let me know if there are any lingering problems.
