### ISSUE TITLE
Tab issue

### ISSUE THREAD

**Issue by spctr01** [Etesam913/slick-fox#6]
Cant move a tab from one firefox window to another

**Comment by SoPat712** [comment]
+1 on this issue, this is a major problem.

**Comment by Etesam913** [comment]
It seems like I can do this. See gif below. Some clarification on what you mean would be helpful.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/55665282/89567401-97134700-d7ef-11ea-9dbf-257c48868032.gif)

**Comment by SoPat712** [comment]
Never mind the +1, all I had to do was to switch off dark theme, it seems as though dark theme doesn't work or something.

**Comment by spctr01** [comment]
@SoPat712  @Etesam913 

Yes it worked by turning dark mode off
