### ISSUE TITLE
Right click dialog box enlarge

### ISSUE THREAD

**Issue by rizalripin** [Etesam913/slick-fox#8]
When I right click on any page, the dialog box is enlarge (appears to increase in height).
Also some elements like text and forward/back button is hidden especially when it is greyed out.

Here what it looks without userchrome.css:
https://imgur.com/MQEq35d

Here with userchrome.css:
https://imgur.com/wtoWEiF

Firefox v79.0
Windows 10

**Comment by Etesam913** [comment]
### The styles should hopefully be fixed with the new commit that I just pushed. This is using the Firefox radiance theme.

![deimsyjumzrnfqtl5uye](https://user-images.githubusercontent.com/55665282/93737739-eb149800-fbb1-11ea-9a89-d012ec191383.png)
